apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: foo.com
    http:
      paths:
      - backend:
          serviceName: forum-webserver  # ServerPool1
          servicePort: 80
        path: /path1                    # HTTPContentRouting1
      - backend: 
          serviceName: image-webserver  # ServerPool2
          servicePort: 80
        path: /path2                    # HTTPContentRouting2
  - host: bar.com
    http:
      paths:
      - backend:
          serviceName: forum-webserver  # ServerPool1
          servicePort: 80
        path: /path3                    # HTTPContentRouting3
      - backend:
          serviceName: image-webserver  # ServerPool2
          servicePort: 80
        path: /path1                    # HTTPContentRouting4
